### ISSUE TITLE
Splash Screen Error

### ISSUE THREAD

**Issue by davis123123** [davis123123/iNGAGE#2]
FATAL EXCEPTION: Thread-4
                                                                 Process: ingage.ingage20, PID: 11110
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources$Theme android.content.Context.getTheme()' on a null object reference
                                                                     at android.app.AlertDialog.resolveDialogTheme(AlertDialog.java:222)
                                                                     at android.app.AlertDialog$Builder.<init>(AlertDialog.java:452)
                                                                     at ingage.ingage20.MySQL.IdentityHandler.onPreExecute(IdentityHandler.java:128)
                                                                     at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:613)
                                                                     at android.os.AsyncTask.execute(AsyncTask.java:560)
                                                                     at ingage.ingage20.SplashActivity$1.run(SplashActivity.java:40)
                                                                     at java.lang.Thread.run(Thread.java:761)

**Comment by ViWu** [comment]
The error happens only when you're previously/currently signed in to the app and calls the identity handler. You can remove the lines that use the handler, since the user information is already cached. Also add in the go to main function under the "session.isLoggedIn() == true" condition or else the thread gets stuck.
